CREATE TABLE IF NOT EXISTS job_descriptions (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  normalized_url    TEXT          NOT NULL,
  url               TEXT          NOT NULL,
  status            VARCHAR(20)   NOT NULL,
  http_status       INTEGER       NULL,
  ats               VARCHAR(20)   NULL,
  body_text         TEXT          NULL,
  body_html_sha256  CHAR(64)      NULL,
  extractor         VARCHAR(40)   NOT NULL,
  fetched_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
  error             TEXT          NULL,
  latency_ms        INTEGER       NULL,
  CONSTRAINT uq_job_descriptions_normalized_url UNIQUE (normalized_url)
);

CREATE INDEX IF NOT EXISTS ix_job_descriptions_fetched_at
  ON job_descriptions(fetched_at);

CREATE INDEX IF NOT EXISTS ix_job_descriptions_status
  ON job_descriptions(status);

ALTER TABLE scored_results
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'snippet';

ALTER TABLE scored_results
  ADD COLUMN IF NOT EXISTS job_description_id INTEGER NULL
  REFERENCES job_descriptions(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_scored_results_job_description_id
  ON scored_results(job_description_id);
