#!/bin/sh
set -eu

if [ -n "${NEW_RELIC_LICENSE_KEY:-}" ] && [ "${NEW_RELIC_ENABLED:-true}" != "false" ]; then
  export NEW_RELIC_LOG="${NEW_RELIC_LOG:-stdout}"
  export NEW_RELIC_LOG_LEVEL="${NEW_RELIC_LOG_LEVEL:-info}"
  export NEW_RELIC_APPLICATION_LOGGING_ENABLED="${NEW_RELIC_APPLICATION_LOGGING_ENABLED:-true}"
  export NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED="${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED:-true}"
  export NEW_RELIC_DISTRIBUTED_TRACING_ENABLED="${NEW_RELIC_DISTRIBUTED_TRACING_ENABLED:-true}"
  exec newrelic-admin run-program "$@"
fi

exec "$@"
